### ISSUE TITLE
bug: "Special" highlight group is not being set

### ISSUE THREAD

**Issue by ficd0** [Aliqyan-21/darkvoid.nvim#15]
I noticed a weird behavior where certain things, like curly braces in lua, have this bright cyan color that isn't actually specified anywhere in the config. I did some digging and it turns out there are a bunch of highlights, like say `@constructor`, that inherit from the `Special` highlight group. This group isn't being set to anything by the setup function. I'm working on a fix at the moment, PR should be ready soon.

**Comment by Aliqyan-21** [comment]
Yes @ficcdaf the problem is not about setting the special highlight color but to fix the curly bracket colors to be consistent with other bracket colors for consistency with other languages too and with treesitter.

Thank you for pointing out this wierd behaviour the problem was that apparently in lua curly braces are treated specially by Tree-sitter due to the @constructor.lua group, which is linked to the Special highlight group rather than directly to @punctuation.bracket. This is likely the reason why curly brackets are not inheriting the @punctuation.bracket color settings I've defined in treesitter.lua file.

**Comment by Aliqyan-21** [comment]
I thus fixed it in #aed411aa985e62846c0cdda952aaf8318bf69f02 in recent commit, Thank you for pointing it out, but the special highlight not required for now, whenever something will behave wierdly we will try to normalize it and thus Darkvoid will remain minimal and consitent everytime.
