### ISSUE TITLE
Color scheme show error in lazyvim

### ISSUE THREAD

**Issue by DawieMalmsteel** [Aliqyan-21/darkvoid.nvim#19]
Hi i using lazyvim and darkvoid but it show error here:

```lua
                         Failed to run `config` for lualine.nvim

.../Local/nvim-data/lazy/LazyVim/lua/lazyvim/plugins/ui.lua:108: attempt to index global 'Snacks' (a nil value)

# stacktrace:
  - LazyVim\lua\lazyvim\plugins\ui.lua:108 _in_ **values**
  - darkvoid.nvim\lua\darkvoid\plugins\lualine.lua:57 _in_ **setup**
  - darkvoid.nvim\lua\darkvoid\config.lua:22 _in_ **load_plugins**
  - darkvoid.nvim\lua\darkvoid\config.lua:39 _in_ **setup**
  - darkvoid.nvim\lua\darkvoid\colors.lua:175 _in_ **setup**
  - darkvoid.nvim\lua\darkvoid\init.lua:23 _in_ **load**
  - darkvoid.nvim\colors\darkvoid.lua:1
  - LazyVim\lua\lazyvim\config\init.lua:217
  - LazyVim\lua\lazyvim\config\init.lua:213 _in_ **setup**
  - LazyVim\lua\lazyvim\init.lua:7 _in_ **setup**
  - ~\AppData\Local\nvim/lua/config/lazy.lua:17
  - ~\AppData\Local\nvim\init.lua:2
``` 

Other color scheme can work fine. Here is my colorscheme config:
```lua
return {
  {
    "aliqyan-21/darkvoid.nvim",
    lazy = false,
    priority = 1000,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      -- colorscheme = "kanagawa",
      -- colorscheme = "hybrid",
      -- colorscheme = "default",
      -- colorscheme = "nightfly",
      colorscheme = "darkvoid",
      -- colorscheme = "tokyonight",
      -- colorscheme = "rose-pine-moon",
    },
  },
}

```

**Comment by Aliqyan-21** [comment]
Hello @Tekitori19, sorry for the inconvinience.

> After some investigation, I came to these conclusions:

### Problem
- error comes from file `ui.lua` within LazyVim, where the global Snacks variable is accessed but is nil.
- the integration with darkvoid.nvim is indirectly triggerring this issue by using the affected code in LazyVim.
-  Other color schemes are working fine because maybe their setups are not triggering the specific part of LazyVim's ui.lua configuration.
- the error is tracing back to darkvoid\plugins\lualine.lua, indicating the lualine configuration in darkvoid.nvim might be influencing this behavior.


### Solution

- One possible solution I can suggest is turning the lualine plugin off in the config.

#### Example in my config I would do like this (do this according to your setup):

```lua
  {
    "aliqyan-21/darkvoid.nvim",
    priority = 1000,
    config = function()
      require("darkvoid").setup({
        transparent = true,
        glow = false,
        colors = {
          plugins = {
            lualine = false -- make this to false
          },
        },
      })
      vim.cmd.colorscheme("darkvoid")
    end,
  },
```

Try this in your config and see if it resolves the problem @Tekitori19.

### Alternative
I think it is because of snack.nvim, try disabling that plugin by doing -> 
`enabled = false` in it's config, i.e, snacks-dashboard.lua.

And see if it fixes the issue than we can do something to make it compatible with snacks.nvim plugin.

Thank You!

**Comment by DawieMalmsteel** [comment]
Thank you so much my man, you fixed that.
